### ISSUE TITLE
Upgrade to use node version 14 (at least) 

### ISSUE THREAD

**Issue by itpmngt** [dwp/node-logger#10]
Hi

Having a library that requires Node ^14.0.0 or above - but when NPM installing 

The engine "node" is incompatible with this module. Expected version ">=10.0.0 <14.0.0". Got "14.7.0"

Is there a reason of incompatibility with Node 14?
(if not, any chance to remove the requirement from package.json? - happy to submit a PR

Best,

Joe Rosa

**Comment by itpmngt** [comment]
BTW, this is used on a DWP project

**Comment by tomwrightgov** [comment]
upgrade the node version to remove support for older versions and now just supports the LTS versions.
